added the reload extension command
IgKniteDev/IgKnite pull request #285
Opened 2024-10-08 19:37 UTC by iyad-f

- [x] cogs.admin has been added
- [x] reloadext command has been added to cogs.admin

2024-10-08 19:43 UTC, hitblast requested changes
Needs some changes I guess.

2024-10-08 19:43 UTC, hitblast commented on core/bot.py
> +class IgKnite(commands.Bot):
The docstring mentions that it's an extension of `AutoShardedBot` but it inherits the `Bot` class. Mind having a look?

2024-10-08 20:41 UTC, iyad-f commented on core/bot.py
> +class IgKnite(commands.Bot):
Oh sorry this is a testing thing it was meant to be AutoshardedBot

2024-10-09 03:09 UTC, hitblast approved these changes
LGTM!

2024-10-09 03:09 UTC, merged

2024-10-11 05:53 UTC, ultralegendary commented on cogs/admin.py
> +    @commands.command(name='reloadext')
hey @hitblast this should be @commands.slash_commands right? 
@iyad-f , Can you provide a example of how to use this command. I am not able to use this command. Wanted to know if there is any other way of using command than "slash"

2024-10-11 10:25 UTC, iyad-f commented on cogs/admin.py
> +    @commands.command(name='reloadext')
it is not going to be a slash command since we don't wanna go with the overhead of registring it to just one guild where admins is present, we rather go with a prefixed command which only owners of the bot will be able to use. As for the second part of the question how to use this, its simple ?reloadext <extiontion_path> e.g. ?reloadext cogs.admin